apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-publicis
  namespace: hello-xke
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: publicis.allowed.org
    http:
      paths:
      - path: /pseday
        backend:
          serviceName: hello-publicis
          servicePort: 8080
