apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-world
  namespace: hello-xke
  labels:
    app.kubernetes.io/name: go-hello-world
    app.kubernetes.io/instance: for-a-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: go-hello-world
      app.kubernetes.io/instance: for-a-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-hello-world
        app.kubernetes.io/instance: for-a-service
    spec:
      containers:
      - name: go-hello-world
        image: clook/go-hello-world
        ports:
        - containerPort: 8080
