apiVersion: v1
kind: Service
metadata:
  name: hello-lb
  namespace: hello-xke
spec:
  selector:
    app.kubernetes.io/name: go-hello-world
    app.kubernetes.io/instance: for-a-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
